site_name: Package Docs
plugins:
  - glightbox
  - search
copyright: "&copy; APAC Corp, Inc."
extra_css:
  - docs/assets/css/extra.css
extra:
  # analytics:
  #   provider: google
  #   property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: assets/img/ZetaLogoIcon.png
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qUtxnK2NMf
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/Zeta/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Zeta/
theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/img/ZetaLogoIcon.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'custom'
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
    font:
      text: Roboto
      code: Roboto Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes


nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
    - Purpose: "purpose.md"
    - Roadmap: "roadmap.md"
    - Design: "design.md"
    - Flywheel: "flywheel.md"
    - Bounties: "bounties.md"
    - Metric: "metric.md"
    - Distribution: "distribution"
    - Research: "research.md"
    - Demos: "demos.md"
    - Architecture: "architecture.md"
    - Checklist: "checklist.md"
    - Hiring: "hiring.md"
- Zeta:
    - Overview: "zeta/index.md"
    - zeta.nn:
      - zeta.nn.biases: 
        - Xpos: "zeta/nn/biases/xpos.md"
        - RelativePositionBias: "zeta/nn/biases/relative_bias.md"
        - AlibiPositionalBias: "zeta/nn/biases/alibi.md"
      - zeta.nn.embeddings:
        - MultiWay: "zeta/nn/embeddings/multiway.md"
        - RotaryEmbeddings: "zeta/nn/embeddings/rope.md"
        - TruncatedRotaryEmbedding: "zeta/nn/embeddings/truncated_rope.md"
      - zeta.nn.modules:
        - Lora: "zeta/nn/modules/lora.md"
        - TokenLearner: "zeta/nn/modules/token_learner.md"
      - zeta.nn.attention:
        - FlashAttention: "zeta/nn/attention/flash_attention.md"
        - MultiQueryAttention: "zeta/nn/attention/multiquery.md"
        - MultiheadAttention: "zeta/nn/attention/multihead.md"
        - FlashAttentionTwo: "zeta/nn/attention/flash2.md"
        - BaseAttention: "zeta/nn/attention/base.md"
      - zeta.nn.architecture:
        - Decoder: "zeta/nn/architecture/decoder.md"
        - Transformer: "zeta/nn/architecture/transformer.md"
    - zeta.training:
      - train: "zeta/training/train.md"
      - zeta.training.loss:
        - Nebula: "zeta/training/nebula.md"
      - zeta.training.optimizers:
        - DecoupledLionW: "zeta/training/optimizers/decoupled_lion.md"
        - SophiaG: "zeta/training/optimizers/sophia.md"
    - zeta.tokenizers:
        - MultiModalTokenizer: "zeta/tokenizers/multi_modal_tokenizer.md"
        - LanguageTokenizerGPTX: "zeta/tokenizers/language_tokenizer.md"
        - SentencePieceTokenizer: "zeta/tokenizers/sentencepiece.md"
- Examples:
    - Overview: "examples/index.md"
    - FlashAttention: "examples/nn/attentions/flash.md"
    